config/routes.rb
# frozen_string_literal: true

# == Route Map
#

Rails.application.routes.draw do
  resources :pipelines do
    member do
      post 'run', to: 'pipelines#run', as: :run
    end
  end

  resources :shopping_lists
  resources :shopping_selections
  resources :errands
  resources :budgets
  resources :brands
  resources :sales
  resources :packages
  resources :users
  resources :stores
  resources :products
  resources :items
  resources :departments

  root 'home#index'
end

app/models/store.rb
# frozen_string_literal: true

# == Schema Information
#
# Table name: stores
#
#  id          :bigint           not null, primary key
#  coordinates :point
#  location    :string           not null
#  name        :string           not null
#  created_at  :datetime         not null
#  updated_at  :datetime         not null
#
class Store < ApplicationRecord
  has_many :shopping_lists, inverse_of: :alternate_store
  has_many :shopping_lists, inverse_of: :recommend_store

  def to_s
    "#{location.titleize} #{name.titleize}"
  end

  def inspect
    "Store ##{id}: #{name.titleize} in #{location.titleize}"
  end

  validates :name, :location, presence: true

  validates :name, uniqueness: { scope: :location }
end

app/controllers/stores_controller.rb
# frozen_string_literal: true

class StoresController < ApplicationController
  before_action :set_store, only: %i[show edit update destroy]

  # GET /stores or /stores.json
  def index
    @stores = Store.all
  end

  # GET /stores/1 or /stores/1.json
  def show; end

  # GET /stores/new
  def new
    @store = Store.new
  end

  # GET /stores/1/edit
  def edit; end

  # POST /stores or /stores.json
  def create
    @store = Store.new(store_params)

    respond_to do |format|
      if @store.save
        format.html { redirect_to store_url(@store), notice: 'Store was successfully created.' }
        format.json { render :show, status: :created, location: @store }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @store.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /stores/1 or /stores/1.json
  def update
    respond_to do |format|
      if @store.update(store_params)
        format.html { redirect_to store_url(@store), notice: 'Store was successfully updated.' }
        format.json { render :show, status: :ok, location: @store }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @store.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /stores/1 or /stores/1.json
  def destroy
    @store.destroy

    respond_to do |format|
      format.html { redirect_to stores_url, notice: 'Store was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_store
    @store = Store.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def store_params
    params.require(:store).permit(:name, :location, :coordinates)
  end
end

app/helpers/stores_helper.rb
# frozen_string_literal: true

module StoresHelper
end

app/views/stores/_form.html.erb
<%= form_with(model: store) do |form| %>
  <% if store.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(store.errors.count, "error") %> prohibited this store from being saved:</h2>

      <ul>
        <% store.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.label :location, style: "display: block" %>
    <%= form.text_field :location %>
  </div>

  <div>
    <%= form.label :coordinates, style: "display: block" %>
    <%= form.text_field :coordinates %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/stores/_store.html.erb
<div id="<%= dom_id store %>">
  <p>
    <strong>Name:</strong>
    <%= store.name %>
  </p>

  <p>
    <strong>Location:</strong>
    <%= store.location %>
  </p>

  <p>
    <strong>Coordinates:</strong>
    <%= store.coordinates %>
  </p>

</div>

app/views/stores/edit.html.erb
<h1>Editing store</h1>

<%= render "form", store: @store %>

<br>

<div>
  <%= link_to "Show this store", @store %> |
  <%= link_to "Back to stores", stores_path %>
</div>

app/views/stores/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Stores</h1>

<div id="stores">
  <% @stores.each do |store| %>
    <%= render store %>
    <p>
      <%= link_to "Show this store", store %>
    </p>
  <% end %>
</div>

<%= link_to "New store", new_store_path %>

app/views/stores/new.html.erb
<h1>New store</h1>

<%= render "form", store: @store %>

<br>

<div>
  <%= link_to "Back to stores", stores_path %>
</div>

app/views/stores/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @store %>

<div>
  <%= link_to "Edit this store", edit_store_path(@store) %> |
  <%= link_to "Back to stores", stores_path %>

  <%= button_to "Destroy this store", @store, method: :delete %>
</div>