config/routes.rb
# frozen_string_literal: true

# == Route Map
#

Rails.application.routes.draw do
  resources :pipelines do
    member do
      post 'run', to: 'pipelines#run', as: :run
    end
  end

  resources :shopping_lists
  resources :shopping_selections
  resources :errands
  resources :budgets
  resources :brands
  resources :sales
  resources :packages
  resources :users
  resources :stores
  resources :products
  resources :items
  resources :departments

  root 'home#index'
end

app/models/pipeline.rb
# == Schema Information
#
# Table name: pipelines
#
#  id            :bigint           not null, primary key
#  target        :string           not null
#  website       :string           not null
#  created_at    :datetime         not null
#  updated_at    :datetime         not null
#  department_id :bigint           not null
#  store_id      :bigint           not null
#
# Indexes
#
#  index_pipelines_on_department_id  (department_id)
#  index_pipelines_on_store_id       (store_id)
#
# Foreign Keys
#
#  fk_rails_...  (department_id => departments.id)
#  fk_rails_...  (store_id => stores.id)
#
class Pipeline < ApplicationRecord
  belongs_to :department
  belongs_to :store
end

app/controllers/pipelines_controller.rb
class PipelinesController < ApplicationController
  before_action :set_pipeline, only: %i[ show edit update destroy run ]

  # GET /pipelines or /pipelines.json
  def index
    @pipelines = Pipeline.all
  end

  # GET /pipelines/1 or /pipelines/1.json
  def show
  end

  # GET /pipelines/new
  def new
    @pipeline = Pipeline.new
  end

  # GET /pipelines/1/edit
  def edit
  end

  def run
    new_sales = Extract::WebScrapingPipeline.crawl!(@pipeline)

    notice = new_sales ? 'Success!' : 'Failure.'

    redirect_to(sales_path, notice: notice, new_sales: new_sales)
  end

  # POST /pipelines or /pipelines.json
  def create
    @pipeline = Pipeline.new(pipeline_params)

    respond_to do |format|
      if @pipeline.save
        format.html { redirect_to pipeline_url(@pipeline), notice: "Pipeline was successfully created." }
        format.json { render :show, status: :created, location: @pipeline }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @pipeline.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /pipelines/1 or /pipelines/1.json
  def update
    respond_to do |format|
      if @pipeline.update(pipeline_params)
        format.html { redirect_to pipeline_url(@pipeline), notice: "Pipeline was successfully updated." }
        format.json { render :show, status: :ok, location: @pipeline }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @pipeline.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /pipelines/1 or /pipelines/1.json
  def destroy
    @pipeline.destroy

    respond_to do |format|
      format.html { redirect_to pipelines_url, notice: "Pipeline was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_pipeline
      @pipeline = Pipeline.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def pipeline_params
      params.require(:pipeline).permit(:target, :department_id, :store_id, :website)
    end
end

app/helpers/pipelines_helper.rb
module PipelinesHelper
end

app/views/pipelines/_form.html.erb
<%= form_with(model: pipeline) do |form| %>
  <% if pipeline.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(pipeline.errors.count, "error") %> prohibited this pipeline from being saved:</h2>

      <ul>
        <% pipeline.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :target, style: "display: block" %>
    <%= form.text_field :target, value: pipeline.target, required: true %>
  </div>

  <div>
    <%= form.label :department_id, 'Department', style: "display: block" %>
    <%= form.select :department_id, options_from_collection_for_select(Department.all, :id, :name, pipeline.department_id), required: true  %>
  </div>

  <div>
    <%= form.label :store_id, 'Store', style: "display: block" %>
    <%= form.select :store_id, options_from_collection_for_select(Store.all, :id, :name, pipeline.store_id), required: true %>
  </div>

  <div>
    <%= form.label :website, style: "display: block" %>
    <%= form.text_field :website, value: pipeline.website, required: true %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/pipelines/_pipeline.html.erb
<div id="<%= dom_id pipeline %>">
  <p>
    <strong>Target Selector:</strong>
    <pre>
      <code>
        <%= pipeline.target %>
      </code>
    </pre>
  </p>

  <p>
    <strong>Department:</strong>
    <%= pipeline.department %>
  </p>

  <p>
    <strong>Store:</strong>
    <%= pipeline.store %>
  </p>

  <p>
    <strong>Website:</strong>
    <%= pipeline.website %>
  </p>

</div>

app/views/pipelines/edit.html.erb
<h1>Editing pipeline</h1>

<%= render "form", pipeline: @pipeline %>

<br>

<div>
  <%= link_to "Show this pipeline", @pipeline %> |
  <%= link_to "Back to pipelines", pipelines_path %>
</div>

app/views/pipelines/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Pipelines</h1>

<div id="pipelines">
  <% @pipelines.each do |pipeline| %>
    <%= render pipeline %>
    <p>
      <%= button_to "Run this pipeline", run_pipeline_path(pipeline) %>
    </p>
  <% end %>
</div>

<%= link_to "New pipeline", new_pipeline_path %>

app/views/pipelines/new.html.erb
<h1>New pipeline</h1>

<%= render "form", pipeline: @pipeline %>

<br>

<div>
  <%= link_to "Back to pipelines", pipelines_path %>
</div>

app/views/pipelines/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @pipeline %>

<%= notice %>

<div>
  <!-- TODO: ActiveJob in background and ActionCable to notify front-end -->
  <%= form_tag(run_pipeline_path(@pipeline), method: "post" ) do %>
    <%= submit_tag("Run this Web Scraping Pipeline") %>
  <% end %>
</div>

<div>
  <%= link_to "Edit this pipeline", edit_pipeline_path(@pipeline) %> |
  <%= link_to "Back to pipelines", pipelines_path %>

  <%= button_to "Destroy this pipeline", @pipeline, method: :delete %>
</div>