config/routes.rb
# frozen_string_literal: true

# == Route Map
#

Rails.application.routes.draw do
  resources :pipelines do
    member do
      post 'run', to: 'pipelines#run', as: :run
    end
  end

  resources :shopping_lists
  resources :shopping_selections
  resources :errands
  resources :budgets
  resources :brands
  resources :sales
  resources :packages
  resources :users
  resources :stores
  resources :products
  resources :items
  resources :departments

  root 'home#index'
end

app/models/sale.rb
# frozen_string_literal: true

# == Schema Information
#
# Table name: sales
#
#  id         :bigint           not null, primary key
#  date       :date             not null
#  price      :decimal(, )      not null
#  quantity   :integer          default(1), not null
#  created_at :datetime         not null
#  updated_at :datetime         not null
#  package_id :bigint           not null
#  store_id   :bigint           not null
#  user_id    :bigint           not null
#
# Indexes
#
#  index_sales_on_package_id  (package_id)
#  index_sales_on_store_id    (store_id)
#  index_sales_on_user_id     (user_id)
#
# Foreign Keys
#
#  fk_rails_...  (package_id => packages.id)
#  fk_rails_...  (store_id => stores.id)
#  fk_rails_...  (user_id => users.id)
#
class Sale < ApplicationRecord
  include ActionView::Helpers::NumberHelper

  validates :price, presence: true, numericality: { greater_than: 0 }
  validates :package, uniqueness: { scope: [:date, :store] }
  validates :package, uniqueness: { scope: [:date, :pipeline] }

  has_many :shopping_selections, inverse_of: :best_matching_deal
  has_many :shopping_selections, inverse_of: :better_alternate_deal

  belongs_to :pipeline, optional: true
  belongs_to :store
  belongs_to :package
  belongs_to :product, optional: true, inverse_of: :sales
  belongs_to :item, optional: true, inverse_of: :sales

  delegate :brand, to: :product
  delegate :product, to: :package
  delegate :item, to: :product

  accepts_nested_attributes_for :package

  scope :invalid, -> { with_packages.where(packages: { unit_measurement: nil }) }

  scope :with_packages, -> { joins(:package) }
  scope :with_package, -> (sought_package) { with_packages.where(packages: sought_package ) }

  scope :with_products, -> { joins(package: :product) }
  scope :with_product, -> (sought_product) { with_products.where(packages: { products: sought_product }) }

  scope :with_brands, -> { joins(package: { product: :brand } ) }
  scope :with_brand, -> (sought_brand) { with_brands.where(packages: { products: { brands: sought_brand } } ) }

  scope :with_items, -> { joins(package: { product: :item }) }
  scope :with_item, -> (sought_item) { with_items.where(packages: { products: { items: sought_item } }) }

  def total_measurement
    return unless package.unit_measurement && package.unit_count

    number_to_human(quantity * package.unit_count * package.unit_measurement, units: package.measurement_units)
  end

  def unit_cost
    total_measurement.to_f / price
  end

  def self.best_deal_for_brand(sought_brand)
    with_brand(sought_brand).order(:price).limit(1).first
  end

  def self.find_cheapest_sale_for_package(sought_package)
    with_package(sought_package).order(:price).limit(1).first
  end

  def self.find_cheapest_sale_for_product(sought_product)
    with_product(sought_product).order(:price).limit(1).first
  end

  def self.find_cheapest_sale_for_item(sought_item)
    with_item(sought_item).order(:price).limit(1).first
  end
end

app/controllers/sales_controller.rb
# frozen_string_literal: true

class SalesController < ApplicationController
  before_action :set_sale, only: %i[show edit update destroy]

  # GET /sales or /sales.json
  def index
    @sales = Sale.all
  end

  # GET /sales/1 or /sales/1.json
  def show; end

  # GET /sales/new
  def new
    @sale = Sale.new
  end

  # GET /sales/1/edit
  def edit; end

  # POST /sales or /sales.json
  def create
    @sale = Sale.new(sale_params)

    respond_to do |format|
      if @sale.save
        format.html { redirect_to sale_url(@sale), notice: 'Sale was successfully created.' }
        format.json { render :show, status: :created, location: @sale }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @sale.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /sales/1 or /sales/1.json
  def update
    respond_to do |format|
      if @sale.update(sale_params)
        format.html { redirect_to sale_url(@sale), notice: 'Sale was successfully updated.' }
        format.json { render :show, status: :ok, location: @sale }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @sale.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /sales/1 or /sales/1.json
  def destroy
    @sale.destroy

    respond_to do |format|
      format.html { redirect_to sales_url, notice: 'Sale was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_sale
    @sale = Sale.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def sale_params
    params.require(:sale).permit(:price, :package_id, :store_id, :user_id, :date, :quantity)
  end
end

app/helpers/sales_helper.rb
# frozen_string_literal: true

module SalesHelper
end

app/views/sales/_form.html.erb
<%= form_with(model: sale) do |form| %>
  <% if sale.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(sale.errors.count, "error") %> prohibited this sale from being saved:</h2>

      <ul>
        <% sale.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :price, style: "display: block" %>
    <%= form.text_field :price %>
  </div>

  <div>
    <%= form.label :package_id, style: "display: block" %>
    <%= form.text_field :package_id %>
  </div>

  <div>
    <%= form.label :store_id, style: "display: block" %>
    <%= form.text_field :store_id %>
  </div>

  <div>
    <%= form.label :user_id, style: "display: block" %>
    <%= form.text_field :user_id %>
  </div>

  <div>
    <%= form.label :date, style: "display: block" %>
    <%= form.date_field :date %>
  </div>

  <div>
    <%= form.label :quantity, style: "display: block" %>
    <%= form.number_field :quantity %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/sales/_sale.html.erb
<tr id="<%= dom_id sale %>">
  <td>
    <p><strong><%= number_to_currency(sale.price) %></strong></p>
  </td>
  <td>
    <p><%= sale.package %></p>
  </td>
  <td>
    <p><%= sale.store %></p>
  </td>
  <td>
    <p>Measurement: <%= sale.total_measurement %></p>
  </td>
  <td>
    <p><%= sale.details %></p>
  </td>
</tr>

app/views/sales/edit.html.erb
<h1>Editing sale</h1>

<%= render "form", sale: @sale %>

<br>

<div>
  <%= link_to "Show this sale", @sale %> |
  <%= link_to "Back to sales", sales_path %>
</div>

app/views/sales/index.html.erb
<p style="color: green">
  <%= notice %>
</p>

<h1>Sales</h1>

<% @sales.group_by(&:date).each do |date, sales| %>
  <%= date %>
  <div id="invalid-sales" class="grid">
    <% sales.each do |sale| %>
      <%= link_to(sale) do %>
        <%= render sale %>
      <%- end %>
    <% end %>
  </div>
<% end %>
<%= link_to "New sale" , new_sale_path %>

app/views/sales/new.html.erb
<h1>New sale</h1>

<%= render "form", sale: @sale %>

<br>

<div>
  <%= link_to "Back to sales", sales_path %>
</div>

app/views/sales/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @sale %>

<div>
  <%= link_to "Edit this sale", edit_sale_path(@sale) %> |
  <%= link_to "Back to sales", sales_path %>

  <%= button_to "Destroy this sale", @sale, method: :delete %>
</div>